version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: go mod download

      - run:
          name: Run tests
          command: go test -v ./...
      - run:
          name: build
          command: GOOS=linux GOARCH=amd64 go build -o main ./cmd/main.go
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy_prod:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          configure-default-region: false
      - run:
          name: Zip Function
          command: zip main.zip ./main
      - run:
          name: Deploy Function
          command: aws lambda update-function-code --function-name recipes --zip-file fileb://./main.zip

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_prod:
          requires:
            - build
          filters:
            branches:
              only: /^master$/
